---
abstract: 'Build and use the experimental 2.0.x branch Fast Light Toolkit'
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  Archive::Extract: 0
  CPAN::Meta::Converter: 0
  CPAN::Meta::Validator: 0
  Carp: 0
  Config: 0
  Cwd: 0
  Digest::MD5: 0
  ExtUtils::CBuilder: 0.27
  ExtUtils::MM: 0
  File::Basename: 0
  File::Fetch: 0
  File::Find: 0
  File::Find::Rule: 0
  File::Path: 2.07
  File::ShareDir: 0
  File::Spec: 0
  File::Temp: 0
  JSON: 0
  Module::Build: 0.3624
  Perl::Tidy: 0
  TAP::Harness: 3.18
  Test::More: 0.88
  YAML::Tiny: 1.46
  base: 0
  perl: 5.008
configure_requires:
  Module::Build: 0.3624
  YAML::Tiny: 1.46
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
keywords:
  - Alien
  - FLTK
  - Fast
  - Light
  - Toolkit
  - widget
  - FL
  - GUI
  - UI
  - window
  - 2.0.x
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-FLTK2
no_index:
  directory:
    - t
    - example
    - inc
    - share
provides:
  Alien::FLTK2:
    file: lib/Alien/FLTK2.pm
    version: 0.08550
requires:
  File::ShareDir: 1.00
  File::Spec::Functions: 0
  YAML::Tiny: 0
resources:
  bugtracker: http://github.com/sanko/alien-fltk2/issues
  homepage: http://sanko.github.com/fltk-perl/
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: git://github.com/sanko/alien-fltk2.git
  x_ChangeLog: http://github.com/sanko/alien-fltk2/commits
version: 0.08550
